apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-java-web-app-vulnerable
  labels:
    app.kubernetes.io/part-of: tanzu-java-web-app-vulnerable
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  - name: testing_pipeline_matching_labels
    value:
      apps.tanzu.vmware.com/language: java
      apps.tanzu.vmware.com/pipeline: test
  - name: testing_pipeline_params
    value:
      source-sub-path: .
  source:
    git:
      url: https://github.com/benwilcock/tanzu-java-web-app
      ref:
        branch: vulnerable
